### ISSUE TITLE
There is already a project called p2 for provisioning

### ISSUE THREAD

**Issue by mickaelistria** [square/p2#77]
Eclipse p2 ( https://www.eclipse.org/equinox/p2/ ) is a very popular project for provisioning of Eclipse plugins, applications, OSGi artifacts (and could be used for other things).
Having 2 projects called p2 may fore sure be confusing for many people. You should probably think about renaming your project to something more unique. What about simply Platyplus or Platyplus-Platform ?

cc @prapicault

**Comment by anthonybishopric** [comment]
Thanks for reporting this. I appreciate the desire to not confuse people. These projects are indeed similar in structure, although very different in intent. I will speak with the team here and make a determination about what to do next.

**Comment by anthonybishopric** [comment]
Thanks again for reporting this. We've come to the conclusion that 1) the projects are sufficiently different that anyone who might use both would be able to distinguish them based on their roles (one is for provisioning, one is for long-running service deployment) and 2) naming things is hard. There are also lots of projects called "platypus" and we don't want to name it anything longer than that.
